# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802e0499bb2dd2664c470f9220fa589fecda8eda0a2b200970ddca988c83b9ef7d9f60a95bc96b7de4a8ecb493f5e9dcba1b37a9645ab1ad24d729b3fdefc919

test:
  secret_key_base: c084f6dec3a66dad94f2d97a746b61dbd4c0ce59517b153ef4008c99a3b7317571e71323f241d7807ab64146bdd7e5edf6106e8e5c49d50aef852b83a16f38cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
